[theme]

# Primary accent for interactive elements
primaryColor = '#03ffa7'

# Background color for the main content area
backgroundColor = '#111212'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#000000'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
